"""Regenerate the two public saved examples with the actual Dynare solver."""

from __future__ import annotations

import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from api.runner import run_simulation, validate_result  # noqa: E402


OUTPUTS = {
    "unilateral_10": REPO_ROOT / "web" / "data" / "saved_unilateral_10.json",
    "bilateral_10": REPO_ROOT / "web" / "data" / "saved_bilateral_10.json",
}


def main() -> None:
    for preset, output_path in OUTPUTS.items():
        print(f"Solving {preset} ...", flush=True)
        result = run_simulation(
            {
                "scenario": {
                    "preset": preset,
                    "horizon": 80,
                    "initialTau21": 1.0,
                    "initialTau12": 1.0,
                    "targetRatePercent": 10.0,
                    "pathProfile": "step",
                    "rebateType": "lumpsum",
                },
                "parameters": {},
                "variables": ["*"],
            }
        )
        result["mode"] = "saved model result"
        result["message"] = "Saved result generated by the public Octave/MATLAB and Dynare model."
        result.pop("cacheHit", None)
        validate_result(result, require_complete=True)
        output_path.write_text(
            json.dumps(result, separators=(",", ":"), allow_nan=False),
            encoding="utf-8",
        )
        print(f"Wrote {output_path} ({len(result['series'])} series)", flush=True)


if __name__ == "__main__":
    main()
